# format = '$all$directory$character'
add_newline = false
# minimal left prompt
format = """$os$directory$character"""
# rest of the prompts to the right
right_format = """$all"""

[os]
format = '[$symbol]($style)'
style= 'bold cyan'
disabled = false

[os.symbols]
Macos = ' '
Arch = '󰣇 '

[directory]
truncation_length = 8
truncation_symbol = '…/'

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'

[golang]
version_format = 'v${major}.${minor}'
format = '[ $version ](bold cyan)'

[python]
symbol = ' '
version_format = 'v${major}.${minor}'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[lua]
symbol = '󰢱 '
style = 'bold blue'
format = '[$symbol($version )]($style)'

[nodejs]
symbol = ' '
style = "bold green"
version_format = 'v${major}.${minor}'
format = '[$symbol($version )]($style)'

[c]
style = 'bold 149'
version_format = 'v${major}.${minor}'
format = '[$name ($version )]($style)'

[package]
symbol ='󰏗 '
version_format = 'v${major}.${minor}'
format = '[$symbol$version]($style) '

[git_branch]
symbol = ' '
style = 'bold red'
format = '[$symbol($branch)]($style)'

[git_status]
style = 'bold red'
format = ' ([\[$all_status$ahead_behind\]]($style) )'
disabled = false

[memory_usage]
symbol = '󰍛 '
format = '$symbol[${ram}( | ${swap})]($style) '
threshold = -1
style = 'bold dimmed green'
disabled = true

[custom.docker]
command = 'docker ps -q | wc -l' # shows output of command
symbol = ' 󰡨 󰜎'
style = "bold blue"
when = '''docker ps -q | grep -c .''' # only display if more than 0 running containers
# format = "[\($symbol $output\)]($style)"
format = "[$output$symbol]($style)"
detect_files = [] 
