# format = '$all$directory$character'
add_newline = false
# minimal left prompt
format = """$os$directory$character"""
# rest of the prompts to the right
right_format = """$all"""

[os]
format = '[$symbol]($style)'
style= 'bold cyan'
disabled = false

[os.symbols]
Macos = ' '
Arch = '󰣇 '

[directory]
truncation_length = 8
truncation_symbol = '…/'

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'

[golang]
format = '[ $version](bold cyan)'

[lua]
symbol = '󰢱 '
style = 'bold blue'
format = '[$symbol($version )]($style)'

[nodejs]
symbol = ' '
style = "bold green"
version_format = 'v${major}.${minor}'
format = '[$symbol($version )]($style)'

[package]
symbol ='󰏗 '
format = '[$symbol$version]($style) '

[git_branch]
symbol = '󰊢 '
style = 'bold red'
format = '[\($symbol($branch)\)]($style)'

[git_status]
style = 'bold red'
format = ' ([\[$all_status$ahead_behind\]]($style) )'
disabled = false

[memory_usage]
symbol = '󰍛 '
format = '$symbol[${ram}( | ${swap})]($style) '
threshold = -1
style = 'bold dimmed green'
disabled = false

